### ISSUE TITLE
Kanban review

### ISSUE THREAD

**Issue by redmarverick** [redmarverick/Final-Capstone-Backend#20]
Group: @redmarverick @Javed-Shahbaz @SergioPeralta22 @Balikuddembe 
Project link: https://github.com/redmarverick/Final-Capstone-Backend/projects/1
Front End Repository: https://github.com/redmarverick/Final-Capstone-Frontend
![image](https://github.com/redmarverick/Final-Capstone-Backend/assets/16127046/0e7264e1-8d96-4a0e-9711-3b1847e2f582)

**Comment by redmarverick** [comment]
![image](https://github.com/redmarverick/Final-Capstone-Backend/assets/16127046/0e7264e1-8d96-4a0e-9711-3b1847e2f582)

**Comment by Meltrust** [comment]
Hi @redmarverick,

## Wow, you did it 🎉 
![Brilliant](https://media.giphy.com/media/d31w24psGYeekCZy/giphy.gif)

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

### To highlight

- The tasks have descriptions, assignees and have been pointed according to spec✔️ 


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
