### ISSUE TITLE
Javed and Nylbert - create main page - [2Pt]

### ISSUE THREAD

**Issue by seperalta22** [redmarverick/Final-Capstone-Backend#4]
- [ ] Create the main page
- [ ]  Set up the layout of the page
- [ ]  Add the required design

![image](https://github.com/redmarverick/Final-Capstone-Backend/assets/78930134/d2c5b2e0-6aee-48cc-acbc-f677be00f934)

**Comment by seperalta22** [comment]
This card belongs to the main page of the application, where the list of cars will be shown, and aims to fulfill task 3 of the core requirements.

**Comment by Balikuddembe** [comment]
Thank you @SergioPeralta22 for this clarification.I have got you clearly well.Let me adjust this feature
